version: "3"
services:
  develop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    #   - "9929:9929"
    #   - "9230:9230"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=1
    # command: gatsby develop -H 0.0.0.0
